language: go
go_import_path: go.etcd.io/etcd

arch:
  - amd64
  - arm64
sudo: required

services: docker

go:
  - 1.13.3
  - tip

notifications:
  on_success: never
  on_failure: never

env:
  matrix:
    - TARGET=linux-arm64-test

matrix:
  fast_finish: true
  allow_failures:
    - go: 1.13.3
      env: TARGET=linux-arm64-test

script:
  - echo "TRAVIS_GO_VERSION=${TRAVIS_GO_VERSION}"
  - >
    case "${TARGET}" in
      linux-amd64-fmt)
        docker run --rm \
          --volume=`pwd`:/go/src/go.etcd.io/etcd gcr.io/etcd-development/etcd-test:go${TRAVIS_GO_VERSION} \
          /bin/bash -c "GOARCH=amd64 PASSES='fmt bom dep' ./test"
        ;;
      linux-amd64-integration-1-cpu)
        docker run --rm \
          --volume=`pwd`:/go/src/go.etcd.io/etcd gcr.io/etcd-development/etcd-test:go${TRAVIS_GO_VERSION} \
          /bin/bash -c "GOARCH=amd64 CPU=1 PASSES='integration' ./test"
        ;;
      linux-amd64-integration-2-cpu)
        docker run --rm \
          --volume=`pwd`:/go/src/go.etcd.io/etcd gcr.io/etcd-development/etcd-test:go${TRAVIS_GO_VERSION} \
          /bin/bash -c "GOARCH=amd64 CPU=2 PASSES='integration' ./test"
        ;;
      linux-amd64-integration-4-cpu)
        docker run --rm \
          --volume=`pwd`:/go/src/go.etcd.io/etcd gcr.io/etcd-development/etcd-test:go${TRAVIS_GO_VERSION} \
          /bin/bash -c "GOARCH=amd64 CPU=4 PASSES='integration' ./test"
        ;;
      linux-amd64-functional)
        docker run --rm \
          --volume=`pwd`:/go/src/go.etcd.io/etcd gcr.io/etcd-development/etcd-test:go${TRAVIS_GO_VERSION} \
          /bin/bash -c "./build && GOARCH=amd64 PASSES='functional' ./test"
        ;;
      linux-amd64-unit)
        docker run --rm \
          --volume=`pwd`:/go/src/go.etcd.io/etcd gcr.io/etcd-development/etcd-test:go${TRAVIS_GO_VERSION} \
          /bin/bash -c "GOARCH=amd64 PASSES='unit' ./test"
        ;;
      all-build)
        docker run --rm \
          --volume=`pwd`:/go/src/go.etcd.io/etcd gcr.io/etcd-development/etcd-test:go${TRAVIS_GO_VERSION} \
          /bin/bash -c "GOARCH=amd64 PASSES='build' ./test \
            && GOARCH=386 PASSES='build' ./test \
            && GO_BUILD_FLAGS='-v' GOOS=darwin GOARCH=amd64 ./build \
            && GO_BUILD_FLAGS='-v' GOOS=windows GOARCH=amd64 ./build \
            && GO_BUILD_FLAGS='-v' GOARCH=arm ./build \
            && GO_BUILD_FLAGS='-v' GOARCH=arm64 ./build \
            && GO_BUILD_FLAGS='-v' GOARCH=ppc64le ./build \
            && GO_BUILD_FLAGS='-v' GOARCH=s390x ./build"
        ;;
      linux-amd64-grpcproxy)
        sudo HOST_TMP_DIR=/tmp TEST_OPTS="PASSES='build grpcproxy'" make docker-test
        ;;
      linux-amd64-coverage)
        sudo HOST_TMP_DIR=/tmp make docker-test-coverage
        ;;
      linux-amd64-fmt-unit-go-tip)
        GOARCH=amd64 PASSES='fmt unit' ./test
        ;;
      linux-386-unit)
        docker run --rm \
          --volume=`pwd`:/go/src/go.etcd.io/etcd gcr.io/etcd-development/etcd-test:go${TRAVIS_GO_VERSION} \
          /bin/bash -c "GOARCH=386 PASSES='unit' ./test"
        ;;
      linux-arm64-test)
        ls
      ;;
    esac
